# Generated by Django 5.2.14 on 2026-06-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='Description',
            new_name='description',
        ),
    ]
